workflows:
  myupiflow-android:
    name: myupiflow Android only (AAB + APK)
    max_build_duration: 90
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: "3.35.3"
        # Secure vars to set in Codemagic UI if signing:
        # KEYSTORE_BASE64, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
    scripts:
      - name: Install OpenJDK 17
        script: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-17-jdk-headless
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      - name: Setup keystore (optional)
        script: |
          if [ ! -z "$KEYSTORE_BASE64" ]; then
            mkdir -p android/app
            echo "$KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks
            printf '%s\n' "storePassword=$KEYSTORE_PASSWORD" \
                          "keyPassword=$KEY_PASSWORD" \
                          "keyAlias=$KEY_ALIAS" \
                          "storeFile=$(pwd)/android/app/upload-keystore.jks" \
            > android/key.properties
          fi

      - name: Dependencies
        script: |
          flutter channel $FLUTTER_CHANNEL
          flutter upgrade
          flutter pub get

      - name: Accept licenses
        script: |
          yes | flutter doctor --android-licenses || true

      - name: Build AAB
        script: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          flutter clean
          flutter build appbundle --release --no-shrink -v

      - name: Build universal APK
        script: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          flutter build apk --release --no-shrink -v

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
