workflows:
  myupiflow-android:
    name: myupiflow Android APK Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: "3.35.3"
        # Secrets are set in Codemagic UI
        # KEYSTORE_BASE64
        # KEYSTORE_PASSWORD
        # KEY_ALIAS
        # KEY_PASSWORD
    scripts:
      - name: Set up Flutter
        script: |
          flutter channel $FLUTTER_CHANNEL
          flutter upgrade
          flutter --version

      - name: Decode and set up keystore (if provided)
        script: |
          if [ ! -z "$KEYSTORE_BASE64" ]; then
            echo "Decoding keystore..."
            mkdir -p android/app
            echo "$KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks

            # Write key.properties safely
            cat <<'EOF' > android/key.properties
storePassword=$KEYSTORE_PASSWORD
keyPassword=$KEY_PASSWORD
keyAlias=$KEY_ALIAS
storeFile=$(pwd)/android/app/upload-keystore.jks
EOF

          else
            echo "No keystore provided, APK will be unsigned"
          fi

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Accept Android licenses
        script: |
          yes | flutter doctor --android-licenses || true

      - name: Build APK (release split per ABI)
        script: |
          flutter clean
          flutter build apk --release --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
